version: 2
jobs:
  build:
    docker:
      - image: heliconwave/circleci:v8
    steps:
      - checkout
      - run:
          name: Build
          command: make all
      - run:
          name: Unit Test
          command: make gtests && make unit-tests
      - run:
          name: Component Tests
          command: make component-tests
      - run:
          name: Build CMake
          command: rm -rf build/ && mkdir build && cd build/ && cmake .. && cmake --build . -- -j36
      - run:
          name: Run CTest
          command: build/tests/run_gtests
