version: 2
jobs:
  build:
    docker:
      - image: heliconwave/circleci:v1
    steps:
      - checkout
      - run:
          name: Build
          command: make
      - run:
          name: Test
          command: make test