version: 2
jobs:
  build:
    docker:
      - image: heliconwave/circleci:v16
    steps:
      - checkout
      - run:
          name: Print Container Metadata
          command: lsb_release -a
      - run:
          name: Build CMake Debug
          command: rm -rf build/ && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -- -j$(nproc)
      - run:
          name: Build CMake Release
          command: rm -rf build/ && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -- -j$(nproc)
      - run:
          name: Build CMake WebAssembly
          command: cd /tmp/emsdk && ./emsdk activate sdk-tag-1.38.31-64bit && ./emsdk_env.sh && export PATH=$PATH:/tmp/emsdk/emscripten/tag-1.38.31 &&
                   cd /tmp/workspace && rm -rf build/ && mkdir build && cd build/ && emcmake cmake -DCMAKE_CXX_STANDARD=11 -DENABLE_TESTS=OFF -DENABLE_WEBASSEMBLY=ON .. && cmake --build . -- -j$(nproc)
      - run:
          name: Component Tests
          command: cd build && make component-tests
      - run:
          name: Run CTest
          command: cd build && make unit-tests
      - run:
          name: Run micro benchmark
          command: cd build && make benchmark-tests
