version: 2
jobs:
  build:
    docker:
      - image: heliconwave/cplusplusdev:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Print Container Metadata
          command: lsb_release -a
      - run:
          name: Build CMake Debug
          command: rm -rf build/ && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -- -j$(nproc)
      - run:
          name: Build CMake Release
          command: rm -rf build/ && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -- -j$(nproc)
      - persist_to_workspace:
          root: /root/project
          paths:
            - build
  # build-webassembly:
  #   docker:
  #     - image: heliconwave/circleci:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build CMake WebAssembly
  #         command: pwd && cd /tmp/emsdk && ./emsdk activate sdk-tag-$EMSDK_VERSION.$EMSDK_BUILD_VERSION-64bit && . emsdk_env.sh && export PATH=$PATH:/tmp/emsdk/emscripten/tag-$EMSDK_VERSION.$EMSDK_BUILD_VERSION && em++ --version &&
  #                  cd /root/project && em++ --version && pwd && rm -rf build/ && mkdir build && cd build/ && emcmake cmake -DCMAKE_CXX_STANDARD=11 -DENABLE_TESTS=OFF -DENABLE_WEBASSEMBLY=ON .. && cmake --build . -- -j$(nproc)
  test-unit:
    docker:
      - image: heliconwave/cplusplus:latest
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Run CTest
          command: pwd && ls -ltrha && cd build && make unit-tests
  test-component:
    docker:
      - image: heliconwave/cplusplus:latest
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Component Tests
          command: cd build && make component-tests
  test-benchmark:
    docker:
      - image: heliconwave/cplusplus:latest
    steps:
      - checkout
      - attach_workspace:
          at: /root/project
      - run:
          name: Run micro benchmark
          command: cd build && make benchmark-tests
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      # - build-webassembly
      - test-unit:
          requires:
            - build
      - test-component:
          requires:
            - build
      - test-benchmark:
          requires:
            - build
