version: 2
jobs:
  build:
    docker:
      - image: heliconwave/circleci:latest
    steps:
      - checkout
      - run:
          name: Build Libs
          command: make libs     
      - run:
          name: Unit Test
          command: make gtests && make unit-tests
      - run:
          name: Component Tests
          command: make component-tests
      - run:
          name: Build CMake Debug
          command: rm -rf build/ && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . -- -j36
      - run:
          name: Build CMake Release
          command: rm -rf build/ && mkdir build && cd build/ && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . -- -j36
      - run:
          name: Run CTest
          command: cd build && tests/run_gtests
      - run:
          name: Run micro benchmark
          command: cd build && bench/Parser_Benchmark
