name: C/C++ CI

on: [push]

jobs:
  build:
    name: building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: check versions
      run: cmake --version
    - name: cmake configure
      run : mkdir build; cd build; cmake -DENABLE_TESTS=ON -DENABLE_COMPONENT_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug ..
    - name: cmake build
      run: cd build/; pwd; cmake --build .
    - name: cmake run unit tests
      run: cd build/; cmake --build . --target unit-tests
