name: C/C++ CI

on: [push]

jobs:
  build:
    name: building
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-16.04]
    steps:
    - uses: actions/checkout@v1
    - name: check versions
      run: cmake --version
    - name: cmake configure
      run : mkdir build; cd build; cmake -DENABLE_COMPONENT_TESTS=OFF ..
    - name: cmake build
      run: cd build/; ls; pwd; cmake --build .
    - name: run unit-tests
      run: cd build/; ls; pwd; cmake --build . --target unit-tests
